// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BinaryElement: typeof import('./components/BinaryElement.vue')['default']
    BinaryElementArray: typeof import('./components/BinaryElementArray.vue')['default']
    BitArrayInput: typeof import('./components/BitArrayInput.vue')['default']
    BitInput: typeof import('./components/BitInput.vue')['default']
    CustomEdge: typeof import('./components/CustomEdge.vue')['default']
    CustomNode: typeof import('./components/CustomNode.vue')['default']
    KeyGeneration: typeof import('./components/KeyGeneration/KeyGeneration.vue')['default']
    PlainNode: typeof import('./components/PlainNode.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecretNode: typeof import('./components/SecretNode.vue')['default']
    TheBox: typeof import('./components/TheBox.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
  }
}
